using GameStore.Api.Dtos;
using GameStore.Api.Entities;
using GameStore.Api.Repositories;
namespace GameStore.Api.Endpoints;

// extention methods allways must belong to static class
public static class GamesEndpoints
{
    const string GetGameEndpointName = "GetGame";
        
    // IEndpointRouteBuilder is base for MapGroup, MapGet...
    public static RouteGroupBuilder MapGamesEndpoints(this IEndpointRouteBuilder routes)
    {
        //InMemGamesRepository repository = new();  //we're injecting it now

        var group = routes.MapGroup("/games")
            .WithParameterValidation();  //validation (installed nuGet package)

        //app.MapGet("/games", () => games); //note, using lambda 
        //group.MapGet("/", () => games);  // "/" works same as ""
        group.MapGet("/", async(IGamesRepository repository) =>
            (await repository.GetAllAsync()).Select(game => game.AsDto())); //each collection object => DTO

        group.MapGet("/{id}", async (IGamesRepository repository, int id) => 
        {
            //Game? game = games.Find(game => game.Id == id);
            Game? game = await repository.GetAsync(id);

            /*
            if (game is null)
            {
                return Results.NotFound();
            }
            return Results.Ok(game);
            */
            return game is not null ? Results.Ok(game.AsDto()) : Results.NotFound();
        }).WithName(GetGameEndpointName);  // lambda () {} with multiple expressions

        //group.MapPost("/", (IGamesRepository repository, Game game) =>
        group.MapPost("/", async (IGamesRepository repository, CreateGameDto gameDto) =>
        {
           /*
            game.Id = games.Max(game => game.Id) + 1;
            games.Add(game);
            */

            Game game = new()
            {
                Name = gameDto.Name,
                Genre = gameDto.Genre,
                Price = gameDto.Price,
                ReleaseDate = gameDto.ReleaseDate,
                ImageUri = gameDto.ImageUri
            };

            await repository.CreateAsync(game);
            return Results.CreatedAtRoute(GetGameEndpointName, new{id = game.Id}, game); //new{} - anonymous type
        });

        group.MapPut("/{id}", async(int id, UpdateGameDto updatedGameDto, IGamesRepository repository) => 
        {
            //Game? existingGame = games.Find(game => game.Id == id);
            Game? existingGame = await repository.GetAsync(id);
            // safety to avoid conflicts with autogenerated id in future DB
            if (existingGame is null)  
            {
                return Results.NotFound();
            }
            
            existingGame.Name = updatedGameDto.Name;
            existingGame.Genre = updatedGameDto.Genre;
            existingGame.Price = updatedGameDto.Price;
            existingGame.ReleaseDate = updatedGameDto.ReleaseDate;
            existingGame.ImageUri = updatedGameDto.ImageUri;

            await repository.UpdateAsync(existingGame);
            return Results.NoContent();  // common choice for PUT requests
        }); 

        group.MapDelete("/{id}", async(int id, IGamesRepository repository) => 
        {
            //Game? game = games.Find(game => game.Id == id);
            Game? game = await repository.GetAsync(id);
           
            if (game is not null)  
            {
                //games.Remove(game);
                await repository.DeleteAsync(id);
            }
            
            return Results.NoContent();
        }); 
        
        return group; // is a type of RouteGroupBuilder
    }
}
